version: '3'

services:
  db:
    container_name: 919_db
    restart: always
    image: mdillon/postgis:9.6-alpine
    expose:
      - "5432"
    volumes:
      - ./dbdata:/var/lib/postgresql/data

  redis:
    container_name: 919_redis
    restart: always
    image: redis:3.0
    expose:
      - "6379"

  api:
    container_name: 919_api
    build:
      context: .
      dockerfile: ./Dockerfile.api
    volumes:
      - ./src:/code
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    command: ./api.dev.sh

  celery_worker:
    container_name: 919_celery_worker
    build:
      context: .
      dockerfile: ./Dockerfile.api
    volumes:
      - ./src:/code
    depends_on:
      - db
      - redis
    command: ./celery_worker.sh

  celery_beat:
    container_name: 919_celery_beat
    build:
      context: .
      dockerfile: ./Dockerfile.api
    volumes:
      - ./src:/code
    depends_on:
      - celery_worker
    command: ./celery_beat.sh

  celery_flower:
    container_name: 919_celery_flower
    build:
      context: .
      dockerfile: ./Dockerfile.api
    volumes:
      - ./src:/code
    depends_on:
      - celery_worker
    ports:
      - "5555:5555"
    command: ./celery_flower.sh
