---
application_apt_packages:
  - build-essential
  - gcc
  - gdal-bin
  - git
  - libcairo2
  - libffi-dev
  - libfreetype6-dev
  - libgdk-pixbuf2.0-0
  - libgeos-*
  - libjpeg8-dev
  - liblcms2-dev
  - libpango1.0-0
  - libpq-dev
  - libtiff5-dev
  - libwebp-dev
  - libxml2-dev
  - libxslt-dev
  - nodejs
  - npm
  - openssl
  - postgresql-client
  - python-gdal
  - python-psycopg2
  - python-tk
  - python3
  - python3-dev
  - python3-lxml
  - python3-pip
  - shared-mime-info
  - supervisor
  - tcl8.6-dev
  - tk8.6-dev
  - upstart
  - zlib1g-dev

application_node_packages:
  - less
  - yuglify
  - bower
